#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Feb 10 17:18:01 -03 2021
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto b2fcf6881a894c2f9b540abbdcd28fa3 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_Gen_Data_Ctrl_behav xil_defaultlib.tb_Gen_Data_Ctrl -log elaborate.log"
xelab -wto b2fcf6881a894c2f9b540abbdcd28fa3 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_Gen_Data_Ctrl_behav xil_defaultlib.tb_Gen_Data_Ctrl -log elaborate.log

