#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Feb 10 17:18:02 -03 2021
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_Gen_Data_Ctrl_behav -key {Behavioral:sim_1:Functional:tb_Gen_Data_Ctrl} -tclbatch tb_Gen_Data_Ctrl.tcl -log simulate.log"
xsim tb_Gen_Data_Ctrl_behav -key {Behavioral:sim_1:Functional:tb_Gen_Data_Ctrl} -tclbatch tb_Gen_Data_Ctrl.tcl -log simulate.log

