webtalk_init -webtalk_dir /home/fnavarro/cognition_Navarro_Facundo/cognition_Navarro_Facundo.sim/sim_1/behav/xsim/xsim.dir/tb_Gen_Data_Ctrl_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Feb 10 17:19:14 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "413c2e94-d8f2-4a07-9ea2-fd42d1e9b74f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "b2fcf6881a894c2f9b540abbdcd28fa3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "ManjaroLinux" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Manjaro Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496.367 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "14595970 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "6.76_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "115024_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3042379786 -regid "" -xml /home/fnavarro/cognition_Navarro_Facundo/cognition_Navarro_Facundo.sim/sim_1/behav/xsim/xsim.dir/tb_Gen_Data_Ctrl_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/fnavarro/cognition_Navarro_Facundo/cognition_Navarro_Facundo.sim/sim_1/behav/xsim/xsim.dir/tb_Gen_Data_Ctrl_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/fnavarro/cognition_Navarro_Facundo/cognition_Navarro_Facundo.sim/sim_1/behav/xsim/xsim.dir/tb_Gen_Data_Ctrl_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
